<?php
// src/ML/BilletterieBundle/Repository/CommandeRepository.php

namespace ML\BilletterieBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
	//-------------------------------------------------
	//Récupération du nombre de billets en BDD par date
	//@var $datevisite
	//-------------------------------------------------
    public function getQteBilletParDate($dateVisite)
    {
        $totalBillet = $this->createQueryBuilder('c');

        $totalBillet
            ->select('SUM(c.qteBillet) as totalBillet')
            ->where('c.dateVisite = :dateVisite')
            ->setParameter('dateVisite', $dateVisite)
        ;
        return $totalBillet
            ->getQuery()
            ->getSingleScalarResult()
            ;
    }
}
